-- Yacht Today · Chat entre el cliente y el propietario de una reserva.
--
-- Solo existe DESPUÉS de reservar, y a propósito: un chat abierto antes de pagar acaba siendo
-- un intercambio de teléfonos para quedar por fuera, y ahí los dos pierden lo que les protege
-- (el cobro garantizado y la fianza). Una vez pagada la reserva no hay nada que fugar, y sí hay
-- mucho que coordinar: la hora exacta, dónde está el amarre, qué llevar.
--
-- El hilo NO se cierra al terminar el alquiler: es justo entonces cuando aparecen los líos
-- ("me falta un cabo", "¿y mi fianza?"), y si se cierra se van al WhatsApp y no queda rastro
-- de la conversación el día que haya una discusión por la fianza.
--
-- Pega y ejecuta este script entero en Supabase → SQL Editor.

create table if not exists public.mensajes (
  id         bigint generated by default as identity primary key,
  reserva_id bigint not null references public.reservas(id) on delete cascade,
  autor_id   uuid   not null references auth.users(id) on delete cascade,
  texto      text   not null check (length(trim(texto)) between 1 and 2000),
  leido_at   timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists mensajes_reserva_idx on public.mensajes (reserva_id, created_at);

alter table public.mensajes enable row level security;

/* ¿Eres una de las dos personas de esta reserva? Es la única pregunta que importa aquí, y la
   responde el servidor. `security definer` porque hay que mirar `reservas`, cuyo RLS no deja
   ver la fila a quien no participa — sin esto, la política se evaluaría contra una tabla vacía. */
create or replace function public.participa_en_reserva(rid bigint)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.reservas r
     where r.id = rid
       and (r.cliente_id = auth.uid() or r.propietario_id = auth.uid())
  );
$$;

drop policy if exists "mensajes_select_participantes" on public.mensajes;
create policy "mensajes_select_participantes" on public.mensajes
  for select using (public.participa_en_reserva(reserva_id));

-- Se escribe en nombre propio y solo en las reservas de uno: nadie puede meterse en un hilo ajeno
-- ni hacerse pasar por el otro.
drop policy if exists "mensajes_insert_participantes" on public.mensajes;
create policy "mensajes_insert_participantes" on public.mensajes
  for insert with check (
    autor_id = auth.uid() and public.participa_en_reserva(reserva_id)
  );

-- El UPDATE existe solo para marcar como leído, y solo lo hace QUIEN RECIBE el mensaje.
drop policy if exists "mensajes_update_leido" on public.mensajes;
create policy "mensajes_update_leido" on public.mensajes
  for update using (
    autor_id <> auth.uid() and public.participa_en_reserva(reserva_id)
  );

/* Sin esto, la política de arriba permitiría a quien recibe un mensaje REESCRIBIR su texto:
   podría cambiar lo que el otro dijo y luego enseñarlo como prueba en una discusión de fianza.
   Lo único que se puede tocar en un mensaje ajeno es `leido_at`. */
create or replace function public.solo_marcar_leido()
returns trigger
language plpgsql
as $$
begin
  if new.texto is distinct from old.texto
     or new.autor_id is distinct from old.autor_id
     or new.reserva_id is distinct from old.reserva_id
     or new.created_at is distinct from old.created_at then
    raise exception 'Un mensaje no se puede editar: solo marcarse como leído.';
  end if;
  return new;
end;
$$;

drop trigger if exists mensajes_no_editar on public.mensajes;
create trigger mensajes_no_editar
  before update on public.mensajes
  for each row execute function public.solo_marcar_leido();
