-- Yacht Today · "Cuida tu Barco": las recompensas del propietario, de verdad.
--
-- Hasta ahora el programa era un cartel: la web prometía kits y limpiezas, pero al llegar al
-- hito no pasaba nada. El propietario no podía reclamar nada, al admin no le llegaba ningún
-- aviso y no quedaba constancia en ninguna parte de que nadie hubiera ganado algo.
--
-- Hitos (`OWNER_NIVELES` en src/App.jsx), por anuncio y contando solo alquileres finalizados:
--   nivel 1 ·  5 alquileres → un filtro a elegir (aire, aceite o gasoil) + garrafa de 5 L, por correo.
--   nivel 2 · 15 alquileres → 15% de descuento en la limpieza del casco o interior (Spen va al puerto).
--
-- Pega y ejecuta este script entero en Supabase → SQL Editor.

create table if not exists public.recompensas (
  id             bigint generated by default as identity primary key,
  anuncio_id     bigint not null references public.anuncios(id) on delete cascade,
  propietario_id uuid   not null references auth.users(id) on delete cascade,
  nivel          smallint not null check (nivel in (1, 2)),
  -- Solo el nivel 1 (el envío del kit) necesita estos tres:
  filtro         text check (filtro in ('aire', 'aceite', 'gasoil')),
  motor          text,   -- modelo del motor, para que el filtro encaje
  direccion      text,   -- dirección de envío del kit
  telefono       text,   -- para la mensajería
  estado         text not null default 'solicitada' check (estado in ('solicitada', 'enviada')),
  nota_admin     text,   -- nº de seguimiento, o lo que el admin quiera dejar anotado
  created_at     timestamptz not null default now(),
  enviada_at     timestamptz,

  -- Un premio por anuncio y nivel: nadie reclama dos veces el mismo kit.
  unique (anuncio_id, nivel)
);

create index if not exists recompensas_propietario_idx on public.recompensas (propietario_id);
create index if not exists recompensas_estado_idx on public.recompensas (estado);

alter table public.recompensas enable row level security;

-- El propietario ve las suyas; la cuenta de administración las ve todas (es quien las envía).
drop policy if exists "recompensas_select" on public.recompensas;
create policy "recompensas_select" on public.recompensas
  for select using (
    auth.uid() = propietario_id
    or auth.jwt() ->> 'email' = 'yachtoday@gmail.com'
  );

-- Solo se puede reclamar en nombre de uno mismo. Que el hito esté REALMENTE alcanzado lo
-- comprueba el trigger de abajo, no esta política.
drop policy if exists "recompensas_insert_propia" on public.recompensas;
create policy "recompensas_insert_propia" on public.recompensas
  for insert with check (auth.uid() = propietario_id);

-- Marcar una recompensa como "enviada" es exclusivo del admin: si el propietario pudiera
-- actualizar su propia fila, podría darse por servido a sí mismo y desaparecer de la cola.
drop policy if exists "recompensas_update_admin" on public.recompensas;
create policy "recompensas_update_admin" on public.recompensas
  for update using (auth.jwt() ->> 'email' = 'yachtoday@gmail.com');

/* ── La comprobación que de verdad importa ──────────────────────────────────────────
   Esconder el botón en la web no protege nada: cualquiera con la consola del navegador
   puede insertar una fila con la anon key. Es Postgres quien cuenta los alquileres y decide
   si el hito está alcanzado — igual que el trigger que impide auto-aprobarse un anuncio
   (supabase/revision-anuncios.sql). `security definer` para poder contar las reservas del
   anuncio saltándose el RLS de `reservas`. */
create or replace function public.comprobar_recompensa()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  dueno       uuid;
  clase_anun  text;
  minimo      int;
  completadas int;
begin
  select propietario_id, clase into dueno, clase_anun
    from public.anuncios where id = new.anuncio_id;

  if dueno is null or dueno <> new.propietario_id then
    raise exception 'Solo el propietario del anuncio puede reclamar su recompensa.';
  end if;

  -- El material (SUP y kayak) no tiene motor que mantener: no entra en el programa.
  if clase_anun = 'material' then
    raise exception 'El material no entra en "Cuida tu Barco".';
  end if;

  minimo := case new.nivel when 1 then 5 when 2 then 15 end;

  select count(*) into completadas
    from public.reservas
   where anuncio_id = new.anuncio_id
     and estado = 'finalizada';

  if completadas < minimo then
    raise exception 'Todavía no se ha alcanzado el hito: % alquileres finalizados de los % que hacen falta.',
      completadas, minimo;
  end if;

  -- Nadie se reclama una recompensa ya "enviada": eso solo lo marca el admin, después.
  new.estado := 'solicitada';
  new.enviada_at := null;
  new.nota_admin := null;
  return new;
end;
$$;

drop trigger if exists recompensas_comprobar on public.recompensas;
create trigger recompensas_comprobar
  before insert on public.recompensas
  for each row execute function public.comprobar_recompensa();
