-- Yacht Today · Fase 4: reservas reales
-- Pega y ejecuta este script entero en Supabase → SQL Editor (después de schema.sql y storage.sql).

create table if not exists public.reservas (
  id                  bigint generated by default as identity primary key,
  anuncio_id          bigint not null references public.anuncios(id) on delete cascade,
  cliente_id          uuid not null references auth.users(id) on delete cascade,
  propietario_id      uuid references auth.users(id) on delete set null,
  barco               text not null,   -- nombre del anuncio en el momento de reservar
  puerto              text not null,
  zona                text not null,
  cliente_nombre      text not null,   -- nombre del cliente en el momento de reservar
  detalle             text not null,   -- "3 días · con patrón", "2 plazas"…
  subtotal            numeric not null,
  servicio            numeric not null,
  total               numeric not null,
  fianza              numeric not null default 0,
  fianza_estado       text check (fianza_estado in ('retenida', 'liberada')),
  licencia_verificada boolean not null default false,
  inicio_iso          timestamptz not null,
  fin_iso             timestamptz not null,
  estado              text not null default 'confirmada' check (estado in ('confirmada', 'finalizada', 'cancelada')),
  motivo_cancelacion  text,
  resena_estrellas    integer check (resena_estrellas between 1 and 5),
  resena_comentario   text,
  created_at          timestamptz not null default now()
);

create index if not exists reservas_cliente_idx on public.reservas (cliente_id);
create index if not exists reservas_propietario_idx on public.reservas (propietario_id);
create index if not exists reservas_anuncio_idx on public.reservas (anuncio_id);

alter table public.reservas enable row level security;

-- El cliente ve sus propias reservas; el propietario ve las que recibe en sus anuncios
drop policy if exists "reservas_select_propias" on public.reservas;
create policy "reservas_select_propias" on public.reservas
  for select using (auth.uid() = cliente_id or auth.uid() = propietario_id);

-- Solo se puede reservar en nombre de uno mismo
drop policy if exists "reservas_insert_propia" on public.reservas;
create policy "reservas_insert_propia" on public.reservas
  for insert with check (auth.uid() = cliente_id);

-- El cliente puede actualizar su reserva (cancelar, dejar reseña);
-- el propietario puede actualizarla (dar visto bueno a la fianza, cancelar con motivo)
drop policy if exists "reservas_update_relacionadas" on public.reservas;
create policy "reservas_update_relacionadas" on public.reservas
  for update using (auth.uid() = cliente_id or auth.uid() = propietario_id);
