-- Yacht Today · Fase 2: tabla de anuncios (barcos, experiencias y material)
-- Pega y ejecuta este script entero en Supabase → SQL Editor.

create table if not exists public.anuncios (
  id                bigint generated by default as identity primary key,
  clase             text not null check (clase in ('barco', 'experiencia', 'material')),
  propietario_id    uuid references auth.users(id) on delete set null,
  nombre            text not null,
  tipo              text,        -- barco: Motora/Velero/…  · material: Paddle surf/Kayak
  actividad         text,        -- experiencia: Pesca/Submarinismo/…
  puerto            text not null,
  zona              text not null,
  plazas            integer,     -- barco y experiencia
  eslora            numeric,     -- barco
  potencia          integer,     -- barco
  anio              integer,     -- barco
  lista             text,        -- barco: 6ª/7ª
  patron            text,        -- barco: no/opcional/incluido
  duracion          text,        -- experiencia
  anfitrion         text,        -- experiencia
  persona           numeric,     -- experiencia: precio por persona
  hora              numeric,     -- barco y material: precio por hora
  dia               numeric,     -- barco y material: precio por día
  matricula         text,        -- barco
  poliza            text,
  caducidad_seguro  date,
  estado            text not null default 'En revisión' check (estado in ('En revisión', 'Publicado', 'Rechazado')),
  hue               integer not null default 205,
  rating            numeric not null default 5,
  reviews           integer not null default 0,
  descripcion       text,
  created_at        timestamptz not null default now()
);

create index if not exists anuncios_estado_idx on public.anuncios (estado);
create index if not exists anuncios_propietario_idx on public.anuncios (propietario_id);

-- Seguridad: cada fila decide quién puede verla / crearla / editarla
alter table public.anuncios enable row level security;

drop policy if exists "anuncios_select_publicos_o_propios" on public.anuncios;
create policy "anuncios_select_publicos_o_propios" on public.anuncios
  for select using (estado = 'Publicado' or auth.uid() = propietario_id);

drop policy if exists "anuncios_insert_propio" on public.anuncios;
create policy "anuncios_insert_propio" on public.anuncios
  for insert with check (auth.uid() = propietario_id);

drop policy if exists "anuncios_update_propio" on public.anuncios;
create policy "anuncios_update_propio" on public.anuncios
  for update using (auth.uid() = propietario_id);

-- Anuncios de ejemplo (los mismos que hoy están fijos en el código),
-- sin propietario real, para que la web no se vea vacía.
insert into public.anuncios (id, clase, nombre, tipo, puerto, zona, plazas, eslora, potencia, anio, lista, patron, hora, dia, rating, reviews, descripcion, hue, estado) values
(1, 'barco', 'Quicksilver 675 Open', 'Motora', 'Grao de Castellón', 'C. Valenciana', 7, 6.75, 150, 2019, '7ª', 'opcional', 65, 380, 4.9, 42, 'Lancha ágil y familiar, perfecta para un día de calas en el Levante. Solárium a proa, ducha de popa y nevera.', 205, 'Publicado'),
(2, 'barco', 'Bavaria Cruiser 34', 'Velero', 'Port de Sóller, Mallorca', 'Baleares', 8, 10.5, 30, 2015, '6ª', 'incluido', 90, 520, 4.8, 31, 'Velero cómodo para navegar a vela por la Tramuntana. Se alquila siempre con patrón titulado.', 210, 'Publicado'),
(3, 'barco', 'Zodiac Medline 580', 'Neumática', 'Palamós, Girona', 'Costa Brava', 6, 5.8, 100, 2021, '7ª', 'no', 50, 300, 4.7, 58, 'Semirrígida estable y seca para descubrir las calas de la Costa Brava. Se maneja con licencia de navegación, sin titulación.', 195, 'Publicado'),
(4, 'barco', 'Sea Ray Sundancer 290', 'Yate', 'Puerto Banús, Marbella', 'Costa del Sol', 8, 9.0, 260, 2018, '6ª', 'incluido', 140, 900, 5.0, 19, 'Yate con camarote, cocina y baño. Se entrega con patrón, para celebraciones o un día premium.', 218, 'Publicado'),
(5, 'barco', 'Yamaha VX Cruiser', 'Moto de agua', 'Las Palmas de G.C.', 'Canarias', 2, 3.3, 125, 2022, '7ª', 'no', 45, 190, 4.6, 73, 'Moto de agua fácil y divertida en aguas atlánticas. Con licencia básica te la llevas.', 25, 'Publicado'),
(6, 'barco', 'Llaüt tradicional 8m', 'Tradicional', 'Dénia, Alicante', 'Costa Blanca', 5, 8.0, 40, 2010, '6ª', 'incluido', 55, 330, 4.9, 27, 'Llaüt de líneas clásicas para navegar sin prisa, con patrón local que conoce cada cala.', 38, 'Publicado'),
(7, 'barco', 'Beneteau Antares 8', 'Motora', 'Vigo, Pontevedra', 'Rías Baixas', 6, 7.9, 220, 2020, '7ª', 'opcional', 80, 470, 4.8, 24, 'Motora cabinada perfecta para recorrer la ría y las Cíes. Con o sin patrón.', 200, 'Publicado'),
(8, 'barco', 'Lagoon 42 Catamarán', 'Catamarán', 'Puerto de Mahón, Menorca', 'Baleares', 10, 12.6, 60, 2019, '6ª', 'incluido', 180, 1200, 5.0, 64, 'Catamarán espacioso y estable, con 4 camarotes. Se entrega con patrón rumbo a Cala en Bosc.', 208, 'Publicado'),
(9, 'barco', 'Jeanneau Cap Camarat 6.5', 'Motora', 'Puerto de Alicante', 'Costa Blanca', 5, 6.5, 150, 2021, '7ª', 'opcional', 58, 340, 4.6, 33, 'Lancha versátil y económica, ideal para grupos pequeños. Sin patrón con la licencia de navegación.', 202, 'Publicado'),
(10, 'barco', 'Dufour 350 Grand Large', 'Velero', 'Marina Real, Valencia', 'C. Valenciana', 8, 10.3, 30, 2017, '6ª', 'incluido', 95, 540, 4.9, 21, 'Velero moderno y luminoso, salida desde la Marina Real, con patrón titulado.', 214, 'Publicado');

insert into public.anuncios (id, clase, actividad, nombre, puerto, zona, plazas, duracion, persona, anfitrion, rating, reviews, descripcion, hue, estado) values
(101, 'experiencia', 'Pesca', 'Jornada de pesca al curricán', 'Grao de Castellón', 'C. Valenciana', 5, '4 h', 55, 'Carlos', 4.9, 38, 'Salimos al amanecer a pescar al curricán con todo el equipo incluido. Yo llevo el barco, tú disfrutas. Apto para principiantes.', 205, 'Publicado'),
(102, 'experiencia', 'Submarinismo', 'Bautizo de buceo en las Islas Medas', 'L''Estartit, Girona', 'Costa Brava', 4, '3 h', 75, 'Marta', 5.0, 52, 'Inmersión guiada en una de las mejores reservas marinas del Mediterráneo. Equipo y titulado incluidos.', 195, 'Publicado'),
(103, 'experiencia', 'Paddle surf', 'Ruta en paddle surf al atardecer', 'Palma, Mallorca', 'Baleares', 8, '2 h', 30, 'Nil', 4.8, 41, 'Ruta guiada en SUP bordeando la costa al atardecer. Tablas, chaleco y monitor incluidos.', 30, 'Publicado'),
(104, 'experiencia', 'Kayak', 'Kayak entre cuevas y calas', 'Xàbia, Alicante', 'Costa Blanca', 6, '3 h', 35, 'Lucía', 4.9, 29, 'Explora cuevas y calas escondidas en kayak con guía local. Incluye snorkel y avituallamiento.', 200, 'Publicado'),
(105, 'experiencia', 'Puesta de sol', 'Aperitivo náutico al atardecer', 'Puerto Banús, Marbella', 'Costa del Sol', 8, '2.5 h', 60, 'Diego', 4.9, 47, 'Navegación tranquila al atardecer con cava y aperitivo a bordo. Yo piloto, vosotros brindáis.', 218, 'Publicado'),
(106, 'experiencia', 'Pesca', 'Pesca de altura en las Rías', 'Vigo, Pontevedra', 'Rías Baixas', 4, '5 h', 70, 'Manuel', 4.8, 22, 'Salida de pesca de altura con patrón experto. Cañas, cebo y licencia incluidos.', 200, 'Publicado');

insert into public.anuncios (id, clase, tipo, nombre, puerto, zona, hora, dia, rating, reviews, descripcion, hue, estado) values
(201, 'material', 'Paddle surf', 'Tabla SUP hinchable Red Paddle 10''6"', 'Peñíscola, Castellón', 'C. Valenciana', 12, 35, 4.7, 18, 'Tabla de paddle surf todoterreno con remo, hinchador y quilla. Perfecta para calas tranquilas.', 32, 'Publicado'),
(202, 'material', 'Kayak', 'Kayak doble sit-on-top', 'Sanxenxo, Pontevedra', 'Rías Baixas', 14, 40, 4.8, 22, 'Kayak biplaza estable con palas y chalecos. Ideal para explorar la ría en pareja.', 198, 'Publicado'),
(203, 'material', 'Paddle surf', 'Pack 2 tablas SUP rígidas', 'Sitges, Barcelona', 'Costa Brava', 20, 55, 4.6, 12, 'Dos tablas rígidas de gama alta con remos de carbono. Se entregan en playa.', 190, 'Publicado'),
(204, 'material', 'Kayak', 'Kayak individual de travesía', 'Los Cristianos, Tenerife', 'Canarias', 13, 38, 4.9, 16, 'Kayak de travesía ligero y rápido. Chaleco y bidón estanco incluidos.', 205, 'Publicado');

-- Evita que el próximo anuncio real choque con los IDs de ejemplo (1-10, 101-106, 201-204)
select setval(pg_get_serial_sequence('public.anuncios', 'id'), (select max(id) from public.anuncios));
